### ISSUE TITLE
Some questions about NYU datasets

### ISSUE THREAD

**Issue by zsy950116** [zhwzhong/Guided-Depth-Map-Super-resolution-A-Survey#1]
Thank you for your outstanding work. Recently, I am also interested in pursuing related research and have two detailed questions that I would like to confirm with you:

1. Regarding the NYU dataset, there are some invalid pixels at the edges of the images. Do we need to crop them? If so, what is the cropping range?

2. For the NYU dataset, do we need to normalize the LR input?  Can we directly use the initial true value range for input?

**Comment by zhwzhong** [comment]
Thanks for your attention. 

For question 1, we didn't crop the invalid pixels, and these pixels have little impact on the final result.
For question 2, we follow the same settings of DJFR (https://github.com/Yijunmaverick/DeepJointFilter/blob/master/examples/Train/generate_trainingdata.m) to normalize the LR input.

**Comment by zsy950116** [comment]
您好，您的邮件我已经接收。
